plugins {
    id 'com.android.application'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    // Required as a workaround for the AGP <= 8.3.2 Java-only DataStore packaging bug.
    // No Kotlin source files are required.
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.nless.mypdf'
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.nless.mypdf"
        minSdk 29
        targetSdk 34
        versionCode 3
        versionName "1.0.2"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'arm64-v8a'
        }

    }

    packagingOptions {
        jniLibs {
            pickFirsts += ['**/libc++_shared.so']
        }
    }

    buildTypes {
        debug {
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseCrashlytics {
                nativeSymbolUploadEnabled true
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.exifinterface:exifinterface:1.3.7'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'

    implementation platform('com.google.firebase:firebase-bom:34.16.0')
    implementation 'com.google.firebase:firebase-crashlytics-ndk'

    implementation 'com.github.mhiew:android-pdf-viewer:3.2.0-beta.3'
    implementation 'com.tom-roush:pdfbox-android:2.0.27.0'
    implementation "com.github.g-o-d-v:android-pdf-search-engine:0.1.0-alpha03"

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'

}